#ifndef _UNICODE
#define _UNICODE
#define UNICODE_ENCODE_ID_DEFAULT (0x00)
#define UNICODE_ENCODE_ID_VERSION_1_1 (0x01)
#define UNICODE_ENCODE_ID_ISO10646 (0x02)
#define UNICODE_ENCODE_ID_UNICODE2_BMP (0x03)
#define UNICODE_ENCODE_ID_UNICODE2_FULL (0x04)
#define UNICODE_ENCODE_ID_UNICODE_VARIATION_SEQUENCES (0x05)
#define UNICODE_ENCODE_ID_FULL (0x06)
#endif
