#ifndef _FONTS_WINDOWS
#define _FONTS_WINDOWS
#define WINDOWS_ENCODE_ID_SYMBOL (0x00)
#define WINDOWS_ENCODE_ID_UNICODE_BMP (0x01)
#define WINDOWS_ENCODE_ID_SHIFTJIS (0x02)
#define WINDOWS_ENCODE_ID_PRC (0x03)
#define WINDOWS_ENCODE_ID_BIG5 (0x04)
#define WINDOWS_ENCODE_ID_WANSUNG (0x05)
#define WINDOWS_ENCODE_ID_JOHAB (0x06)
#define WINDOWS_ENCODE_ID_RESERVED0 (0x07)
#define WINDOWS_ENCODE_ID_RESERVED1 (0x08)
#define WINDOWS_ENCODE_ID_RESERVED2 (0x09)
#define WINDOWS_ENCODE_ID_UNICODE_FULL (0x0A)
#endif
